### ISSUE TITLE
How to add "Edit/Delete" button as a column in the rendered table?

### ISSUE THREAD

**Issue by snoba** [izimobil/django-rest-framework-datatables#31]
Thanks for your amazing tool 👍 
I have a problem on adding a column for placing "Edit/Delete" buttons. I made my table structure as mentioned on the tutorial. Currently, I do not know how could I add customized HTML as a column on the rendered table.

**Comment by jgarciaISITECH** [comment]
I don't know if it's posible too. If not, it would be a nice feature!

**Comment by izimobil** [comment]
DRF-Datatables has no support for editing or deleting, it just render/filter/order data in a Datatables compatible way.

That said, you can add buttons in javascript with the DataTables features, for example:

```
$(document).ready(function() {
    $('#example').DataTable( {
        "columnDefs": [
            {
                // The `data` parameter refers to the data for the cell.
                // The `rows`argument is an object representing all the data for the current row.
                "render": function ( data, type, row ) {
                    return "<button class='btn btn-danger btn-delete' data-pk='" + data + "'>" + row.name + "</button>";
                },
                "targets": -1  // -1 is the last column, 0 the first, 1 the second, etc.
            }
        ]
    } );
} );
```

See: https://datatables.net/examples/advanced_init/column_render.html

**Comment by matthewhegarty** [comment]
Is this supported?  When I send `targets: 0` the server process crashes with:

```
django.core.exceptions.FieldError: Cannot resolve keyword '0' into field. Choices are: ...
```

The URL sent is:

http://localhost:8000/api/player/?format=datatables&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1570722296362

I've spent most of the afternoon trying to figure this out and I don't think it is going to be possible.  If I follow the example [here](https://datatables.net/reference/option/columns.render) then the results are empty (presumably because no column definitions are specified).  The request is:

http://localhost:8000/api/player/?format=datatables&draw=1&columns%5B0%5D%5Bdata%5D=&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1570719675060

and the response is empty data:
```json
{"recordsTotal":2,"recordsFiltered":2,"data":[{},{}],"draw":1}
```
Specifying the columns works (as per the [example](https://github.com/izimobil/django-rest-framework-datatables)), but this means you cannot get two values into a render function, for example:

```javascript
return '<a href="/player/' + obj.id + '">' + obj.name + '</a>';
```
I think the only way is to render the link server-side and return it as part of the JSON (nasty).
