### ISSUE TITLE
Search and filter doing nothing in custom ViewSet

### ISSUE THREAD

**Issue by Rubyj** [izimobil/django-rest-framework-datatables#36]
Hi,

I have a django rest application with multiple viewsets that are working correctly with datatables and this package. However, I have recently made a custom viewset which overrides the `list()` method of the viewset. Therefore, the `?format=datatables` is not working correctly (the list function is overridden and only that functionality happens). Sorting, paging, and filtering are not working correctly. How can I also get the datatables formatted endpoint on server side processing to correctly paginate, filter, and search even though I have overridden the `list()` method of my viewset.

I tried the following which is pretty much the same as the docs:

Are my annotations breaking things?

```
class ValidationSummaryViewSet(viewsets.ViewSet):
    queryset = TargetConfirmation.objects.values('target_prediction__id').annotate(
        sample_id=F('target_prediction__id'), num_selected=Count('selected'), num_validated=Count('validated'),
        num_has_standard=Count('has_standard'))
    serializer_class = ValidationSummarySerializer

    def list(self, request):
        serializer = self.serializer_class(self.queryset, many=True)
        return Response(serializer.data)
```

Thanks!

**Comment by neighlyd** [comment]
Hey @Rubyj ,

From what I can see here, you aren't running your serializer through either a paginator or a filter when you override `list()`.

If you [look at the code for `list()`](http://www.cdrf.co/3.9/rest_framework.mixins/ListModelMixin.html), you'll see that it runs the queryset through both `self.filter_queryset()` and `self.paginate_queryset()`. The [first method](http://www.cdrf.co/3.9/rest_framework.generics/ListAPIView.html#filter_queryset) checks your queryset filter backend and iterates through it, applying the filters that you have listed. The [second method](http://www.cdrf.co/3.9/rest_framework.generics/ListAPIView.html#paginate_queryset) does something similar, in that it checks your object for a paginator and runs its pagination method.

However, since your `list()` method doesn't call either of these methods, the resulting serializer has no way of being either filtered or paginated, whether through DRF Datatables or any other filtering and pagination package.

I would recommend looking at the source-code for the `list()` method mixin to refactor your own implementation so that you can implement these features.

**Comment by Rubyj** [comment]
@izimobil Thank you for the excellent response. I will do this and attempt to implement this behavior in my implementation of `list()`. Thanks!!

**Comment by neighlyd** [comment]
Hopefully it works!

If you aren't familiar, there are two **really fantastic** websites that break down Django's views and Django Rest Framework's views and serializers into their component methods and mixins. They are really amazing resources. I highly recommend bookmarking them and having a look whenever you get stuck or want to modify existing behaviors.

[Here is the Django Class-Based Views Website](http://ccbv.co.uk/)
[Here is the DRF Class Website](http://www.cdrf.co/)

PS: I'm @neighlyd , not @izimobil. Not that it matters too much, so long as your issue gets resolved.

**Comment by Rubyj** [comment]
Sorry about that. I fixed the tag. Force of habit in this repo. I will definitely take a look and bookmark those as well. Thank you for the resources and the help. I will report back here with the results and close the issue if it works!

**Comment by Rubyj** [comment]
@neighlyd I'm a little confused. The `ViewSet` class I am extending does not have the `self.filter_queryset()` or `self.paginate_queryset()` methods you mentioned. Are you saying I need to make my class extend off of `ListModelMixIn`?

**Comment by neighlyd** [comment]
Both of those methods are defined in [GenericAPIView](http://www.cdrf.co/3.9/rest_framework.generics/GenericAPIView.html). If you want to do any filtering or pagination of your list view queryset, you will need to access them.

The `ViewSet` class does not provide any actions by default. You will either need to implement these methods yourself, add the mixins (which would be an inheritance nightmare and doing a lot of unnecessary work), or change up the ViewSet that you're using.

Unless there's a specific reason you're using `ViewSet` instead of something like `ListAPIView` or `ModelViewSet`, I would recommend switching up your patterns.

[Here is the DRF documentation on class-based views](https://www.django-rest-framework.org/tutorial/3-class-based-views/).

**Comment by Rubyj** [comment]
Ah now I understand. Thanks again!

**Comment by neighlyd** [comment]
Awesome! Glad I could be of help. Good luck with your project 😃

**Comment by Rubyj** [comment]
@neighlyd for reference I solved this issue like so:

```
class ValidationSummaryViewSet(viewsets.ViewSet):
    queryset = TargetConfirmation.objects.values('target_prediction__id').annotate(
        sample_id=F('target_prediction__id'), num_selected=Count('selected'), num_validated=Count('validated'),
        num_has_standard=Count('has_standard'))
    serializer_class = ValidationSummarySerializer
    filter_backends = [DatatablesFilterBackend]
    paginator = DatatablesPageNumberPagination

    def list(self, request):
        paginator = self.paginator()
        if request.query_params.get('format', None) == 'datatables':
            paginator.is_datatable_request = True
        else:
            paginator.is_datatable_request = False
        queryset = self.filter_queryset(queryset)
        page = self.paginate_queryset(queryset, paginator)
        if page is not None:
            serializer = self.serializer_class(page, many=True)
            return self.get_paginated_response(serializer.data, paginator)
        serializer = self.serializer_class(queryset, many=True)
        return Response(serializer.data)        
    
    def filter_queryset(self, queryset):
        for backend in list(self.filter_backends):
            queryset = backend().filter_queryset(self.request, queryset, self)
        return queryset

    def paginate_queryset(self, queryset, paginator):
        if self.paginator is None:
            return None
        return self.paginator.paginate_queryset(queryset=queryset, request=self.request, self=paginator)

    def get_paginated_response(self, data, paginator):
        assert self.paginator is not None
        return self.paginator.get_paginated_response(paginator, data)
```

I probably made this problem overly complicated and will look at switching to a `ModelViewSet` or a `ListApiView`
