### ISSUE TITLE
Using "format" as a GET Param breaks DRF

### ISSUE THREAD

**Issue by davidhtien** [izimobil/django-rest-framework-datatables#4]
See http://www.django-rest-framework.org/api-guide/format-suffixes/#query-parameter-formats

**Comment by izimobil** [comment]
How laconic...
Can you describe the issue, please ? What's the problem with the "format" GET parameter ?

**Comment by davidhtien** [comment]
Ah found out what was wrong, the project I was working on had a drf settings object in it's dev settings and I was only editing the base settings haha, false alarm

**Comment by johnthagen** [comment]
In case anyone else runs into this, I was unable to use `format` as a query parameter to a `ViewSet` because of this. It seems that `format` is reserved for DRF.

To fix the issue, change the query parameter to another name, such as `file_format`.

**Comment by wish7code** [comment]
@johnthagen Think I'm facing the same issue (DRF + Viewset)

/api/?format=json works perfectly fine and returns results
/api/?format=datatables gives 404 error

Could you elaborate where you changed the query parameter name?

**Comment by johnthagen** [comment]
@wish7code what I found was that `format` used as a query parameter is consumed by DRF. If you want to have custom logic associated with a query parameter, you need to pick another query parameter name.

**Comment by chidg** [comment]
The `format` param determines the Renderer class by the content negotiator in `rest_framework.negotiation.DefaultContentNegotiation.filter_renderers`. If none of the available renderer classes match the given format, this method raises a `Http404`. 

One way to fix this would be to override this `filter_renderers` class in order to use a default renderer class regardless of the format kwarg. Personally I didn't want to get too much into the weeds on this and so I found a workaround by creating a custom renderer class.

```

It seems like the `format` kwarg is doing too much work here. For my purposes I just wanted it to determine which serialiser to use in my view - normal json or geojson. However, it's inbuilt purpose is tied up with content negotation and rendering, which are at a lower level and more technical than I would guess the average DRF user usually needs to get.

**Comment by izimobil** [comment]
Hi,
Why do you report the issue here ? It's not related to DRF-datatables (but DRF) or maybe I'm missing something ?

**Comment by chidg** [comment]
Hi @izimobil, correct, it's not related to this repository. This is a DRF issue. The reason I posted here is because my solution might help @davidhtien, and since I came across this issue page by googling the problem, it might help other people with the same problem. If you would prefer not to have this discussion here I will delete my post.

**Comment by izimobil** [comment]
@chidg No, no problem :) It was just to clarify.
