### ISSUE TITLE
DEFAULT_PAGINATION_CLASS not changing to custom paginator

### ISSUE THREAD

**Issue by plug-city** [izimobil/django-rest-framework-datatables#54]
I created a custom pagintor that skips running a `SELECT COUNT(*) AS __count FROM` query.

I have a large database of 6.5million rows so a count query takes a little over 2 seconds.

When I visit the URL http://127.0.0.1:8000/products/api/ the `SELECT COUNT` query is not run as I would expect.

When I visit the URL http://127.0.0.1:8000/products/api/?format=datatables a `SELECT COUNT` query is run which causes the table to take more time to load.

Anyone have any idea on how to fix this? or have a better solution to not run the `SELECT COUNT `query everytime I load a new page?

**Comment by izimobil** [comment]
I guess that's because DRF-datatables pagination classes inherit from DRF ones (and not your custom pagination class), you'll have to create a custom pagination class for DRF-datatables as well.

See: https://github.com/izimobil/django-rest-framework-datatables/blob/master/rest_framework_datatables/pagination.py

**Comment by izimobil** [comment]
Note that DRF-datatables pagination classes also do a count() on the queryset, so even with your paginator you will have to circumvent this call.

**Comment by izimobil** [comment]
This should be fixed now ! https://github.com/izimobil/django-rest-framework-datatables/commit/c5439ab9352d54b0a12a75cad860093c97383138
