### ISSUE TITLE
What does columns.item.name do?

### ISSUE THREAD

**Issue by morenoh149** [izimobil/django-rest-framework-datatables#97]
Trying to interpret the docs and the example. We see code like
```
    $('#albums_post').DataTable({
        "serverSide": true,
        "ajax": {
            "url": "api/post-list/albums/?format=datatables",
            "type": "POST",
            "beforeSend": function(xhr) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token|escapejs }}");
            }
        },
        "columns": [
            {"data": "artist.name", "name": "artist.name"},
        ]
    });
```
Seems like the `"name"` value in a column definition tells the backend what serializer to use. In the above case it's the `ArtistSerializer`. If it said `"name": "foobar.field"` the backend would use the FoobarSerializer.

The docs go on to say
> If you need to filter on multiple fields, you can always pass through multiple variables like so
`'name': 'artist.name, artist__year'`
> This would allow you to filter the artist.name column based upon name or year.

> The values within a single name field are tied together using a logical OR operator for filtering, while those between name fields are strung together with an AND operator. This means that Datatables’ multicolumn search functionality is preserved.

is `'artist.name, artist.year'` demonstrating an OR filter or an AND filter? In either case how do we perform the other type of filtering (if this is an OR how do you do an AND)?

**Comment by slyapustin** [comment]
@morenoh149 Check that section of the docs: https://github.com/izimobil/django-rest-framework-datatables/blob/master/docs/tutorial.rst#a-more-complex-and-detailed-example

**Comment by morenoh149** [comment]
@slyapustin I read that but do not find the answer to my question.

is 'artist.name, artist.year' demonstrating an OR filter or an AND filter? In either case how do we perform the other type of filtering (if this is an OR how do you do an AND)?

**Comment by matthewhegarty** [comment]
> Seems like the "name" value in a column definition tells the backend what serializer to use. In the above case it's the ArtistSerializer.

I think it would be more accurate to say that the 'name' field is used to construct the db query.  The resulting queryset is then passed to the Serializer for rendering in the response.

In the [datatables definition](https://datatables.net/reference/option/columns.name), 'name' is used to give a defined name to a column, in order to make it easier to work with.

In the [django-rest-framework-datatables logic](https://github.com/izimobil/django-rest-framework-datatables/blob/979370ca6e8b2f3431b2ad5feb069e887eae3a29/rest_framework_datatables/filters.py#L41), the 'name' field is translated into a filter parameter for the purposes of searching or filtering using a QuerySet.  For example, if I load up the example application and search for 'A', then I see the following Q object generated:

![q_screenshot](https://user-images.githubusercontent.com/6249838/107785424-7864ae80-6d44-11eb-8873-e17ea8720107.png)

So you can see that the name value is used to derive the model relation in order to search. 

The [column 'data' definition](https://datatables.net/reference/option/columns.data) is used to indicate to datatables where to look for the values for rendering.  So if I have a data definition of 'artist.name', I would expect there to be a nested representation in the response JSON as follows:

```
"artist": {
    "id": 2,
    "name": "The Beatles"
}
```

> is 'artist.name, artist.year' demonstrating an OR filter or an AND filter?

According to the docs, this would be an 'OR' filter.  However, it looks like there is a mistake in the documentation, because the names must be 'relative' to the Album model which is specified in the 'queryset' attribute of the [view](https://github.com/izimobil/django-rest-framework-datatables/blob/979370ca6e8b2f3431b2ad5feb069e887eae3a29/example/albums/views.py#L101).

The correct definition should be:

```
'columns': [
        {'data': 'artist.name', 'name': 'artist.name, year'}
]
```

This works because 'year' is an attribute of the Album model.

> In either case how do we perform the other type of filtering (if this is an OR how do you do an AND)?

The docs say that separate fields should be strung together with 'AND':

```
# This definition should result in an AND query
'columns': [
        {'data': 'artist.name', 'name': 'artist.name'},
	{'data': 'year', 'name': 'year'},
]
```

However, the SQL that results from this does not perform an AND, so it looks like there is a bug here.
